apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apprs
  labels :
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: '105718917616.dkr.ecr.us-east-1.amazonaws.com/ass02-dev-web:v1.0'
        ports: 
        - containerPort: 8080
          protocol: TCP
          env:
          - name: MYSQL_ROOT_PASSWORD
            value : passw
          - name: DBHOST
            value : 10.244.0.7
          - name: DBPORT
            value : "3306"
