kind: Pod
apiVersion: v1
metadata:
  name: sql
  labels: 'app:database'
spec:
  containers:
    - name: mysql
      image: '105718917616.dkr.ecr.us-east-1.amazonaws.com/ass02-dev-datab:v1.0'
      ports:
        - containerPort: 3306
          protocol: TCP
