apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysqlrs
  labels :
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: datab
        image: '105718917616.dkr.ecr.us-east-1.amazonaws.com/ass02-dev-web:v1.0'
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value : passw
