apiVersion: v1
kind: Service
metadata:
  name: nport
  labels:
    app: employees
  namespace: nsweb
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: employees
